const pages=document.querySelectorAll(".card"),noBtn=document.getElementById("noBtn"),yesBtn=document.getElementById("yesBtn"),lockBtn=document.getElementById("lockBtn");let noMoves=0,chosenDateText="",chosenTimeText="";
function vibrate(p=25){if("vibrate"in navigator)navigator.vibrate(p)}
function goTo(id){pages.forEach(p=>{p.classList.remove("active");p.classList.remove("celebrate")});document.getElementById(id).classList.add("active")}
function celebrateCurrentCard(){const a=document.querySelector(".card.active");if(a){a.classList.remove("celebrate");void a.offsetWidth;a.classList.add("celebrate")}}
function moveNoButton(){noMoves++;const x=Math.random()*200-100,y=Math.random()*130-65,r=Math.random()*24-12;noBtn.style.transform=`translate(${x}px, ${y}px) rotate(${r}deg)`;const s=Math.min(1+noMoves*.18,2.25);yesBtn.style.transform=`scale(${s})`;if(noMoves>=5)noBtn.textContent="still no? 😭"}
noBtn.addEventListener("mouseenter",moveNoButton);noBtn.addEventListener("touchstart",e=>{e.preventDefault();moveNoButton()});noBtn.addEventListener("click",()=>goTo("page-no"));
yesBtn.addEventListener("click",()=>{vibrate([20,35,20]);document.body.classList.add("warm");yesBtn.classList.add("pulse");celebrateCurrentCard();burstConfetti();setTimeout(()=>{yesBtn.classList.remove("pulse");goTo("page-mission")},850)});
function lockDate(){const d=document.getElementById("date").value,t=document.getElementById("time").value,e=document.getElementById("error");if(!d||!t){e.textContent="Pick both a date and time first 🙂";return}const o=new Date(`${d}T${t}`);chosenDateText=o.toLocaleDateString("en-SG",{weekday:"long",day:"numeric",month:"long"});chosenTimeText=o.toLocaleTimeString("en-SG",{hour:"numeric",minute:"2-digit"});vibrate([25,45,25]);burstConfetti();lockBtn.textContent="Date secured.";lockBtn.disabled=true;lockBtn.style.opacity=".85";setTimeout(()=>{goTo("page-loading");runLoading()},900)}
const loadingSteps=[{text:"Dispatch received...",sub:"Preparing operation.",progress:18},{text:"10-2",sub:"Proceeding to planning...",progress:36},{text:"Searching for good food...",sub:"Very important tasking.",progress:54},{text:"Checking Singapore traffic...",sub:"Standby...",progress:72},{text:"ETA: Hopefully on time 😂",sub:"Road conditions unpredictable.",progress:88},{text:"Just key in logsheet.",sub:"Date prep completed.",progress:100}];
function runLoading(){const lt=document.getElementById("loadingText"),ls=document.getElementById("loadingSub"),f=document.getElementById("loadingFill");let i=0;function n(){const s=loadingSteps[i];lt.textContent=s.text;ls.textContent=s.sub;f.style.width=`${s.progress}%`;i++;if(i<loadingSteps.length)setTimeout(n,820);else setTimeout(showFinal,950)}f.style.width="0%";n()}
function showFinal(){document.getElementById("finalText").innerHTML=`Be ready on <strong>${chosenDateText}</strong> at <strong>${chosenTimeText}</strong>.<br><br><strong>I'll come pick you up.</strong>`;playDing();burstConfetti();goTo("page-final")}
function playDing(){try{const A=window.AudioContext||window.webkitAudioContext,c=new A(),o=c.createOscillator(),g=c.createGain();o.type="sine";o.frequency.setValueAtTime(880,c.currentTime);o.frequency.exponentialRampToValueAtTime(1320,c.currentTime+.12);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.12,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.35);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.36)}catch(e){}}
function burstConfetti(){const canvas=document.getElementById("confetti"),ctx=canvas.getContext("2d"),ps=[];canvas.width=innerWidth;canvas.height=innerHeight;for(let i=0;i<150;i++)ps.push({x:canvas.width/2,y:canvas.height/2,vx:(Math.random()-.5)*11,vy:(Math.random()-.5)*11-3,size:Math.random()*6+3,life:95,hue:Math.random()*360,rot:Math.random()*360,spin:Math.random()*12-6});function a(){ctx.clearRect(0,0,canvas.width,canvas.height);ps.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.13;p.life--;p.rot+=p.spin;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot*Math.PI/180);ctx.fillStyle=`hsl(${p.hue},90%,65%)`;ctx.fillRect(-p.size/2,-p.size/2,p.size,p.size);ctx.restore()});if(ps.some(p=>p.life>0))requestAnimationFrame(a);else ctx.clearRect(0,0,canvas.width,canvas.height)}a()}
